/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAContract,
  IAContractInterface,
} from "../../IAContract.sol/IAContract";

const _abi = [
  {
    inputs: [],
    name: "changeCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAContract__factory {
  static readonly abi = _abi;
  static createInterface(): IAContractInterface {
    return new utils.Interface(_abi) as IAContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAContract {
    return new Contract(address, _abi, signerOrProvider) as IAContract;
  }
}
