/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAContract__factory } from "./IAContract__factory";
export { IERC20__factory } from "./IERC20__factory";
