/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface AContractInterface extends utils.Interface {
  functions: {
    "changeCaller(string)": FunctionFragment;
    "presentCaller()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "changeCaller" | "presentCaller"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeCaller",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "presentCaller",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "changeCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presentCaller",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    changeCaller(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    presentCaller(overrides?: CallOverrides): Promise<[string]>;
  };

  changeCaller(
    _name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  presentCaller(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    changeCaller(
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    presentCaller(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    changeCaller(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    presentCaller(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    changeCaller(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    presentCaller(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
